name: Build and Deploy Weather App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate


      - name: Compress artifact for deployment
        run: zip release.zip ./app/* -r

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: weather-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: weather-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          mv app/* .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'WeatherForecastingApp'  # Replace with your Azure Web App name      # Adjust if using deployment slots
